appimage build

diff --git a/.github/workflows/appimage.yml b/.github/workflows/appimage.yml
--- a/.github/workflows/appimage.yml
+++ b/.github/workflows/appimage.yml
@@ -86,6 +86,12 @@ jobs:
         env:
           ARCH: x86_64
         run: |
+          export QMAKE="$(command -v qmake6 || true)"
+          if [ -z "${QMAKE}" ]; then
+            echo "qmake6 not found in PATH"
+            exit 1
+          fi
+
           ./linuxdeploy-x86_64.AppImage \
             --appdir AppDir \
             --desktop-file AppDir/usr/share/applications/qsensors.desktop \
